### ISSUE TITLE
Cannot animate "target" of arcRotateCamera

### ISSUE THREAD

**Issue by joenye** [hookex/react-babylon-spring#2]
Many thanks for developing this package. It works great for my use case so far, with one exception:

When I try to animate the "target" property of an arcRotateCamera, I get the error: "TypeError: target.addToRef is not a function".

I've created a [CodeSandbox](https://codesandbox.io/s/6wfud?file=/src/App.js) to reproduce the error.

As you can see in the CodeSandbox example, I can animate the "position" property on, for example, a box. But as soon as I animate the "target" property of an arcRotateCamera, I get the error.

I wonder if it's related to the solution given in [this](https://forum.babylonjs.com/t/arc-rotate-camera-animation-target-animation-freezes-other-properties-animations/12998/4) issue?

@brianzinn Tagging you as well just in case you're aware of a fix :pray:

**Comment by brianzinn** [comment]
hi @joenye - you have found an interesting bug - and thanks for reporting and also for the helpful repro.  After some head scratching - I think it's because `target` is not only a property of the camera, but also a constructor parameter 😄  The constructor parameters don't currently follow the property conversion that properties updates follow.  In other words, the "target", which you are passing as an array isn't automatically converted to a Vector3 in the constructor, but it would be after object instantiation and also on subsequent property updates. Hope that makes sense!  This is something that I would like to fix in the upstream react-babylonjs project.  Let me work on a fix... I may need to decorate the metadata with more info, so it will take me a bit of time...

**Comment by brianzinn** [comment]
@joenye your code sandbox works in `react-babylonjs` 3.0.12 🎉

**Comment by joenye** [comment]
I've just upgraded to 3.0.12 and can confirm this has fixed the issue.

@brianzinn It's incredible how quickly you responded and fixed this. Huge kudos to you - thank you so much!! :rocket: :tada:
